groups:
  - name: websocket.rules
    rules:
      # Zero connections alert
      - alert: WebSocketZeroConnections
        expr: websocket_connections_active == 0
        for: 60s
        labels:
          severity: warning
          service: "websocket-server"
          environment: "{{ $labels.job }}"
        annotations:
          summary: "WebSocket server has zero active connections"
          description: "WebSocket server {{ $labels.instance }} ({{ $labels.job }}) has had zero active connections for more than 60 seconds"

      # High connection count alert
      - alert: WebSocketHighConnectionCount
        expr: websocket_connections_active > 8000
        for: 2m
        labels:
          severity: warning
          service: "websocket-server"
          environment: "{{ $labels.job }}"
        annotations:
          summary: "High WebSocket connection count"
          description: "WebSocket server {{ $labels.instance }} ({{ $labels.job }}) has {{ $value }} active connections (threshold: 8000)"

      # Connection limit reached
      - alert: WebSocketConnectionLimitReached
        expr: websocket_connections_active >= 10000
        for: 30s
        labels:
          severity: critical
          service: "websocket-server"
          environment: "{{ $labels.job }}"
        annotations:
          summary: "WebSocket connection limit reached"
          description: "WebSocket server {{ $labels.instance }} ({{ $labels.job }}) has reached the connection limit with {{ $value }} active connections"

      # High error rate
      - alert: WebSocketHighErrorRate
        expr: rate(websocket_errors_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          service: "websocket-server"
          environment: "{{ $labels.job }}"
        annotations:
          summary: "High WebSocket error rate"
          description: "WebSocket server {{ $labels.instance }} ({{ $labels.job }}) has error rate of {{ $value | printf \"%.2f\" }} errors/sec over the last 5 minutes"

      # High message rate (instead of latency since we removed histogram)
      - alert: WebSocketHighMessageRate
        expr: rate(websocket_messages_total[5m]) > 1000
        for: 2m
        labels:
          severity: info
          service: "websocket-server"
          environment: "{{ $labels.job }}"
        annotations:
          summary: "High WebSocket message rate"
          description: "WebSocket server {{ $labels.instance }} ({{ $labels.job }}) is processing {{ $value | printf \"%.2f\" }} messages/sec over the last 5 minutes"

      # Server down
      - alert: WebSocketServerDown
        expr: up{job=~"websocket-.*"} == 0
        for: 30s
        labels:
          severity: critical
          service: "websocket-server"
          environment: "{{ $labels.job }}"
        annotations:
          summary: "WebSocket server is down"
          description: "WebSocket server {{ $labels.instance }} ({{ $labels.job }}) is down and not responding to health checks"

      # Long shutdown time
      - alert: WebSocketLongShutdownTime
        expr: websocket_shutdown_time_seconds > 30
        for: 1m
        labels:
          severity: warning
          service: "websocket-server"
          environment: "{{ $labels.job }}"
        annotations:
          summary: "WebSocket server shutdown taking too long"
          description: "WebSocket server {{ $labels.instance }} ({{ $labels.job }}) took {{ $value }} seconds to shutdown (threshold: 30s)"

      # High memory usage (only in production environment)
      - alert: WebSocketHighMemoryUsage
        expr: process_resident_memory_bytes{job=~"websocket-.*"} > 1073741824  # 1GB
        for: 5m
        labels:
          severity: warning
          service: "websocket-server"
          environment: "{{ $labels.job }}"
        annotations:
          summary: "High memory usage"
          description: "WebSocket server {{ $labels.instance }} ({{ $labels.job }}) is using {{ $value | printf \"%.0f\" }} bytes of memory (threshold: 1GB)"

      # High CPU usage (only in production environment)
      - alert: WebSocketHighCPUUsage
        expr: rate(process_cpu_seconds_total{job=~"websocket-.*"}[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
          service: "websocket-server"
          environment: "{{ $labels.job }}"
        annotations:
          summary: "High CPU usage"
          description: "WebSocket server {{ $labels.instance }} ({{ $labels.job }}) CPU usage is {{ $value | printf \"%.1f\" }} (threshold: 0.8)" 