global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'websocket-monitor'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # WebSocket Server Blue
  - job_name: 'websocket-blue'
    static_configs:
      - targets: ['websocket-blue:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  # WebSocket Server Green (for blue-green deployment)
  - job_name: 'websocket-green'
    static_configs:
      - targets: ['websocket-green:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik-lb:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Node exporter for system metrics (optional)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Redis metrics (if redis-exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s 