# Dynamic Configuration for Traefik
http:
  middlewares:
    # Rate limiting middleware
    api-ratelimit:
      rateLimit:
        burst: 20
        average: 10
        period: 1s
        
    websocket-ratelimit:
      rateLimit:
        burst: 10
        average: 5
        period: 1s
    
    # Security headers middleware
    security-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          X-Frame-Options: "SAMEORIGIN"
          X-XSS-Protection: "1; mode=block"
          X-Content-Type-Options: "nosniff"
          Referrer-Policy: "no-referrer-when-downgrade"
          Content-Security-Policy: "default-src 'self' http: https: data: blob: 'unsafe-inline'"
          Strict-Transport-Security: "max-age=63072000; includeSubDomains"
        
    # IP whitelist for metrics endpoint
    metrics-whitelist:
      ipWhiteList:
        sourceRange:
          - "172.20.0.0/16"  # Docker network
          - "127.0.0.1/32"   # Localhost
          - "::1/128"        # IPv6 localhost
          
    # Compression middleware
    compression:
      compress: {}
      
    # Timeout middleware for WebSocket connections
    websocket-timeout:
      forwardAuth:
        address: "http://localhost/health"
        trustForwardHeader: true
        
# TLS configuration
tls:
  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
      sniStrict: true 