# Traefik Configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Entry points (ports)
entryPoints:
  web:
    address: ":80"
    # http:
      # redirections:
        # entryPoint:
          # to: websecure
          # scheme: https
          # permanent: true
  websecure:
    address: ":443"
  traefik:
    address: ":8080"

# Certificate configuration
certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@localhost
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

# Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

# API and Dashboard
api:
  dashboard: true
  insecure: true

# Metrics
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true

# Logging
log:
  level: INFO
  format: json

# Access logs
accessLog:
  format: json
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: keep
        Authorization: drop
        Content-Type: keep

# Ping endpoint for health checks
ping:
  entryPoint: "traefik" 