global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'websocket-monitor'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # WebSocket Server Blue
  - job_name: 'websocket-blue'
    static_configs:
      - targets: ['websocket-blue:3001']
        labels:
          instance: 'websocket-blue'
          environment: 'blue'
          service: 'websocket-server'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # WebSocket Server Green (for blue-green deployment)
  - job_name: 'websocket-green'
    static_configs:
      - targets: ['websocket-green:3001']
        labels:
          instance: 'websocket-green'
          environment: 'green'
          service: 'websocket-server'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik-lb:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s